AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: URL Shortener Backend

Globals:
  Function:
    Timeout: 3
    Runtime: python3.13
    MemorySize: 128


Resources:
  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlTable
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GetUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/getUrl
      Handler: app.handler
      Description: Recover the original URL from a short code
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UrlTable
      Events:
        GetUrl:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: get

  CreateUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/createUrl
      Handler: app.handler
      Description: Crear un nuevo short code para una URL
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        CreateUrl:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:
  ApiUrl:
    Description: "URL base del API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"