AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: URL Shortener Backend

Globals:
  Function:
    Timeout: 60
    Runtime: python3.13
    MemorySize: 128

Parameters:
  JwtSecret:
    Type: String
    Description: JWT secret
    Default: secret

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          UrlAuth:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            FunctionPayloadType: TOKEN
            Identity:
              Header: Authorization
              ReauthorizeEvery: 0

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-layer
      Description: Common utilities
      ContentUri: layers/common
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain

  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlTable
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/authorizer
      Handler: app.handler
      Description: JWT validator for protected routes
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTable
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/login
      Handler: app.handler
      Description: Login user
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTable
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /auth/login
            RestApiId: !Ref ApiGatewayApi

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/register
      Handler: app.handler
      Description: Register user
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTable
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /auth/register
            RestApiId: !Ref ApiGatewayApi

  CreateShortCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/crud/createShortCode
      Handler: app.handler
      Description: Creates the short code entry in the database
      Environment:
        Variables:
          URL_TABLE_NAME: !Ref UrlTable
          USER_TABLE_NAME: !Ref UserTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /url
            RestApiId: !Ref ApiGatewayApi
            Auth:
              Authorizer: UrlAuth

  GetUserUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/crud/getUserUrls
      Handler: app.handler
      Description: Retrieve all the urls info for the user
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /url
            RestApiId: !Ref ApiGatewayApi
            Auth:
              Authorizer: UrlAuth

  GetUserUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/crud/redirect
      Handler: app.handler
      Description: Redirect to the original url of the shortcode
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UrlTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UrlTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /{shortCode}
            RestApiId: !Ref ApiGatewayApi

Outputs:
  ApiUrl:
    Description: "URL base del API Gateway"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"