AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: URL Shortener Backend

Globals:
  Function:
    Timeout: 3
    Runtime: python3.13
    MemorySize: 128


Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          UrlAuth:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            FunctionPayloadType: TOKEN
            Identity:
              Header: Authorization
              ReauthorizeEvery: 300

  # UrlTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: UrlTable
  #     AttributeDefinitions:
  #       - AttributeName: shortCode
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: shortCode
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST
  
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/authorizer
      Handler: app.handler
      Description: JWT validator for protected routes
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/login
      Handler: app.handler
      Description: Login user
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /auth/login
            RestApiId: 
              Ref: ApiGatewayApi

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "URL base del API Gateway"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"